alias clock="date +\"%T\""
alias cdp="cd ~/repos/portal"
alias gco="git checkout"
alias gcob="git checkout -b"
alias cdid="cd ~Documents/Repos/internal-docs"
alias glo='git log --oneline --decorate'
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias gfa='git fetch --all --prune'
alias gpf='git push --force-with-lease'
alias gs='git status -s'
alias ga='git add'
alias gaa='git add -A'
alias grb='git rebase'
alias grbi='git rebase -i'
alias gcm='git commit -m'
alias reload='source ~/.zshrc'
alias dotreload='/home/hampus/dotfiles/install.sh'
alias cow=''
source /home/hampus/dotfiles/utils/aliases
